spring.application.name=ICAI

# --- 1. CONEXIÓN A LA BASE DE DATOS H2 ---
# Le decimos que guarde los datos en un archivo llamado "dbdata" en la carpeta de tu proyecto
spring.datasource.url=jdbc:h2:file:./dbdata
spring.datasource.username=sa
spring.datasource.password=

# --- 2. CONSOLA WEB H2 ---
# Encendemos la pantalla de monitores para poder entrar desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- 3. MAGIA DE JPA E HIBERNATE ---
# generate-ddl=true hace que Spring lea tus @Entity y cree los "CREATE TABLE" automáticamente
spring.jpa.generate-ddl=true
# (Opcional pero recomendado para aprender) Imprime el SQL en la consola para que veas qué hace por debajo
spring.jpa.show-sql=true 

# --- 4. CARGA DE DATOS INICIALES (data.sql) ---
# Le dice a Spring que ejecute el archivo data.sql cada vez que arranca
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
# MUY IMPORTANTE: Le dice a Spring "Espera a crear las tablas antes de intentar meter los datos iniciales"
spring.jpa.defer-datasource-initialization=true